### ISSUE TITLE
OScheck

### ISSUE THREAD

**Issue by hectorox** [RehabMan/Laptop-DSDT-Patch#13]
Hi RehabMan,
Can you explain, how to fix the OScheck? I have a Problem: With my self-patched DSDT system hangs on boot (Sometimes after AppleCPUManament completed, and PCI Begin Configuration). I found out that after adding Darwinfix by clover, it is booting "well" no hang. Do you have any Idea?
What I have done so far:
I completely changed the codes for OS/OSI-Loading to OSFX, LINX, AMAC, OSFL,... I read somewhere that this method is more hackintosh compatible, but it didn't help...

For any help I would be very grateful

**Comment by RehabMan** [comment]
No idea without details.  Why don't you diff your own DSDT with the Clover patched one?  

At any rate, not related to the patches in this repo.
