### ISSUE TITLE
ASUS K43E battery patch

### ISSUE THREAD

**Issue by dhnguyen92** [RehabMan/Laptop-DSDT-Patch#14]
Here is the missing patch in ASUS G75VW battery patch for ASUS K43E:

`into method label OLPM code_regex \(\\_SB\.PCI0\.SBRG\.EC0\.B0DC, replace_matched begin (B1B2(\\_SB.PCI0.SBRG.EC0.B0D0,\\_SB.PCI0.SBRG.EC0.B0D1), end;`

**Comment by RehabMan** [comment]
In a way, it is already in the patch.
```
# added for T300LA-DH51T
into method label OLPM code_regex \(\\_SB\.PCI0\.LPCB\.EC0\.B0DC, replace_matched begin (B1B2(\\_SB.PCI0.LPCB.EC0.B0D0,\\_SB.PCI0.LPCB.EC0.B0D1), end;
```

If your LPC device is named SBRG, suggest renaming to LPCB prior to battery patch.
