### ISSUE TITLE
ASUS N550JV hd4600 DSDT fix install

### ISSUE THREAD

**Issue by Sogl** [RehabMan/Laptop-DSDT-Patch#16]
Hi!

I can't install this patch to my DSDT.aml (generated from Windows 8.1 x64 by AIDA64 Engineer):
https://github.com/RehabMan/Laptop-DSDT-Patch/blob/master/graphics/graphics_HD4600_yosemite.txt

I download MaciASL (from your repo) and click "Patch", put contets of this file, but "Apply" button is inactive - shows me 0 changes etc.
I do not have Internet in my Hackintosh to use patches from this repository directly.
What I'm doing wrong?

p.s. I use Clover bootloader. Can I add this fix in Clover?

**Comment by RehabMan** [comment]
Most Haswell laptops have the integrated graphics device (usually GFX0) defined in an SSDT, not DSDT.  Sounds like you're trying to patch the wrong file.  You can also use various Clover features to accomplish the same thing.

**Comment by Sogl** [comment]
>You can also use various Clover features to accomplish the same thing.
Can you give me small description or link, please?

**Comment by RehabMan** [comment]
http://clover-wiki.zetam.org/Home

**Comment by Sogl** [comment]
So much SSDT, which to use?

screen from aida64:
![ssdt](https://cloud.githubusercontent.com/assets/7556290/7549371/180cae8a-f675-11e4-8e39-5cc309437f3b.jpg)

**Comment by RehabMan** [comment]
http://www.tonymacx86.com/yosemite-laptop-support/152573-guide-patching-laptop-dsdt-ssdts.html
