### ISSUE TITLE
EHC1/EHC2/XHC1/LAN sleep fix 

### ISSUE THREAD

**Issue by dhnguyen92** [RehabMan/Laptop-DSDT-Patch#19]
Here is the patch to make _PRW method to return the package with 0 in second position. It's based on your Lenovo USB patch, but modified to due with different value in the first position of package.
```
# set _PRW methods to return 0

into method label _PRW parent_adr 0x001D0000 code_regex Return[^(]*\([^(]*\(([^,]*)[^)]*[^,]* replace_matched
begin
Return (Package(){%1,0})
end;
into method label _PRW parent_adr 0x001A0000 code_regex Return[^(]*\([^(]*\(([^,]*)[^)]*[^,]* replace_matched
begin
Return (Package(){%1,0})
end;
into method label _PRW parent_adr 0x00140000 code_regex Return[^(]*\([^(]*\(([^,]*)[^)]*[^,]* replace_matched
begin
Return (Package(){%1,0})
end;

# change the second index in LANC to 0
into method label _PRW parent_adr 0x00190000 code_regex (Return\s+\(.*) replace_matched
begin
Store (0x00, Index (Local0, 0x01))\n
%1
end;
```

**Comment by RehabMan** [comment]
What I do in my patch is just remove them, then add them as a Name.  Name is more efficient.

**Comment by dhnguyen92** [comment]
The problem your patch always set the first argument in return to package to 0x6D, which can be changed in each system. This patch avoid that and is more universal.

**Comment by RehabMan** [comment]
I understand the problem well.  But I choose to convert them to Name.

And I provide two separate patches.  One for 0x0D and the other for 0x6D.  Which are the only two values I've seen so far.

DSDT patches like this one tend to be system specific.  People have to use their brains when using them.

Even your 'LANC' patch is likely to not work on all systems.

In my view these patches are only temporary until we determine how to address the root problem.

**Comment by RehabMan** [comment]
If we find no way to fix instant wake properly, I can update the patches, but I would need to modify them both for the case _PRW is a method and the case _PRW is Name (my U430 uses Name).
