### ISSUE TITLE
Help! Use not full keyboard on laptop dell vostro 3550

### ISSUE THREAD

**Issue by lungkuteo** [RehabMan/Laptop-DSDT-Patch#21]
I need type key ` | ` and ` \ `, but don't type. My laptop is dell vostro 3550, install mac os yossemite. Please help me type full keyboard?

**Comment by RehabMan** [comment]
Not an issue with DSDT.  Issue is your keyboard driver/keylayout chosen.  Choose appropriate keylayout (SysPrefs->Keyboard) or create a custom one with Ukelele.

**Comment by lungkuteo** [comment]
thank you very much!
