### ISSUE TITLE
Battery Patch for Lenovo-G470-i3-2310m.txt

### ISSUE THREAD

**Issue by justry** [RehabMan/Laptop-DSDT-Patch#22]
![battery patch for lenovo-g470-i3-2310m](https://cloud.githubusercontent.com/assets/4385092/8892903/3a1c8b56-33a8-11e5-9cb8-0c87573986ea.png)

I'm so sorry to use the issues feature to submit the battery patch, and please to rename the error pic's filename extension "png" to "txt".

**Comment by RehabMan** [comment]
Link is broken.  If you want to submit a patch, submit the patch + native DSDT here: http://www.tonymacx86.com/yosemite-laptop-support/116102-guide-how-patch-dsdt-working-battery-status.html
