### ISSUE TITLE
Battery patch for ASUS Haswell laptops

### ISSUE THREAD

**Issue by dhnguyen92** [RehabMan/Laptop-DSDT-Patch#23]
Most ASUS Haswell laptops have problems with setting wrong value between battery state. The following patch help it. I hope you can add to ASUS battery patches.

```
into method label FBST code_regex If\s\(CHGS\s\(Zero\)\)[\s]+\{[\s]+Store\s\(0x02,\sLocal0\)[\s]+\}[\s]+Else[\s]+\{[\s]+Store\s\(One,\sLocal0\)[\s]+\} replaceall_matched begin 
If (CHGS (Zero))\n
{\n
     Store (0x02, Local0)\n
}\n
Else\n
{\n
     Store (Zero, Local0)\n
}
end;
```

**Comment by RehabMan** [comment]
Please provide example native DSDT.

**Comment by RehabMan** [comment]
Finally saw a DSDT in the forum this applies to.  Fixed, and closing.
