### ISSUE TITLE
SSDT still have some GFX0

### ISSUE THREAD

**Issue by riverai** [RehabMan/Laptop-DSDT-Patch#25]
Hi,Rehabman.

I have used the patch to rename GFX0 to IGPU,but...

Before:

        Device (GFX0)
        {
            Name (_ADR, 0x00020000)  // _ADR: Address
            Method (_DEP, 0, NotSerialized)  // _DEP: Dependencies
            {
                ADBG ("GFX0 DEP Call")
                If (LEqual (S0ID, One))
                {
                    ADBG ("GFX0 DEP")
                    Return (Package (0x01)
                    {
                        \_SB.PEPD
                    })
                }
                Else
                {
                    ADBG ("GFX0 DEP NULL")
                    Return (Package (0x00) {})
                }
            }

After:

        Device (IGPU)
        {
            Name (_ADR, 0x00020000)  // _ADR: Address
            Method (_DEP, 0, NotSerialized)  // _DEP: Dependencies
            {
                ADBG ("GFX0 DEP Call")
                If (LEqual (S0ID, One))
                {
                    ADBG ("GFX0 DEP")
                    Return (Package (0x01)
                    {
                        \_SB.PEPD
                    })
                }
                Else
                {
                    ADBG ("GFX0 DEP NULL")
                    Return (Package (0x00) {})
                }
            }

Should i rename them manually?

Thanks for your contribution ,sincerely.

**Comment by RehabMan** [comment]
I don't see any issue -- the GFX0 left is inside a sting literal.  The ADBG code does nothing.  In fact, on hacks we replace the code in ADBG so it is only 'Return(0)' (with "Fix ADBG Error").

**Comment by riverai** [comment]
Thanks
