### ISSUE TITLE
battery_ASUS-N55SL.txt report

### ISSUE THREAD

**Issue by itribal** [RehabMan/Laptop-DSDT-Patch#28]
hi，thx for this patch，in the early days i used this patch with my N56VV dsdt， when I set smbios is macbook pro9,2 it’s perfect! 
But if I change smbios from mbp9,2 to mbp10,1 or mba5,2 and others models, battery in the status bar is always display 100% electricity, even battery level is very low.
link file is the original dsdt
https://www.dropbox.com/s/yhms6oy53s5q0x7/dsdt.zip?dl=0
please help me.

**Comment by RehabMan** [comment]
Battery status does not depend on SMBIOS.  You must have some other problem.

You should use the forums for help, not this site.
