### ISSUE TITLE
Surface Book power management and battery patch pls

### ISSUE THREAD

**Issue by cydia2020** [RehabMan/Laptop-DSDT-Patch#34]
It has been released for a while but there;s no patches about it at all, i could help out if you need hardware information. thanks, just pm me

**Comment by RehabMan** [comment]
I'm not writing any patches unless I need them myself.

Patch it yourself by following my guide: http://www.tonymacx86.com/threads/guide-how-to-patch-dsdt-for-working-battery-status.116102/

**Comment by cydia2020** [comment]
So, i actually got 2 batteries and using others machines DSDT to let the NVMe Disk works(my own one won;t work) is that the same process, thanks a lot

**Comment by RehabMan** [comment]
NVMe has nothing to do with battery status.  For multiple batteries, it is best to combine them into one with ACPI.  See SSDT-BATC.dsl in the ACPIBatteryManager github.

**Comment by cydia2020** [comment]
Yeah, sorry but my meaning is that i am using other device's dsdt to let the NVMe driver works, or it get kernel panic on 10.11.4, so, do i just move the whole BAT1 and BAT2 section from my machine to the dsdt that i am using that from another machine and apply the patch, is that it? Thanks

**Comment by RehabMan** [comment]
It is never a good idea to use a DSDT from another computer.  There are many known problems with NVMeGeneric.kext when used as a boot drive (and therefore not recommended).

You should determine what needs to change in your own DSDT to fix the NVMe problem instead of adopting a foreign DSDT.

All off-topic here though...

**Comment by cydia2020** [comment]
OK, thanks a lot

**Comment by cydia2020** [comment]
Hello there, just one more question, what if i got 
        B2TM,   16, 
                B2PV,   16, 
                B2CR,   16, 
                B2AC,   16, 
                B2ME,   16, 
                B2RS,   16, 
                B2RC,   16, 
                B2FC,   16, 
                B2CI,   16, 
                B2CV,   16, 
                B2SL,   8, 
                B2SH,   8, 
                B2CY,   16, 
                B2DC,   16, 
                B2DV,   16, 
                B2SI,   16, 
                B2MD,   16, 
                B2SN,   16, 
                B2MN,   96, 
                B2DN,   64, 
                B2CH,   48, 
this kind of data, which is for battery 2, what to do with this
Thanks

**Comment by RehabMan** [comment]
It depends on whether the data is accessed and how.  It also depends on whether those fields are in the EC or not.

Read guide: http://www.tonymacx86.com/threads/guide-how-to-patch-dsdt-for-working-battery-status.116102/

I'm guessing the "Surface Pro v4" patch already in the repo is a match.
