### ISSUE TITLE
G50-70 DSDT patching don't solve the battery status

### ISSUE THREAD

**Issue by HoshiYamazaki** [RehabMan/Laptop-DSDT-Patch#38]
Hello ;)
I didn't know where to write so I put it here. When I patch DSDT I get "only" 290 warnings but since no error I moved it to Clover EFI partition. Still no battery status.
What info you want to get for helping me?
Thanks.

**Comment by HoshiYamazaki** [comment]
This is zip file:
[DSDT.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/595609/DSDT.zip)

**Comment by RehabMan** [comment]
You need ACPIBatteryManager.kext.
Read the README for further links/information.
