### ISSUE TITLE
Please Help,My mini pc 's video  the size of card is 5mb.

### ISSUE THREAD

**Issue by xpbtmusic** [RehabMan/Laptop-DSDT-Patch#40]
Hi,RehabMan.
    My computer is zhanmei mini pc. The video card intel hd6000 can not be drived, the HDMI interface is connected to the display, recognition memory is always 5MB。

**Comment by xpbtmusic** [comment]
This is the ioreg
[MacBook Pro.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/631256/MacBook.Pro.zip)
.

**Comment by RehabMan** [comment]
You are not running a new enough version of OS X.
This is not the place to ask for help.
Use the forums.
