### ISSUE TITLE
DO NOT POST QUESTIONS OR PROBLEMS HERE

### ISSUE THREAD

**Issue by R1MnTnA** [RehabMan/Laptop-DSDT-Patch#43]
Please use the online forums. Use Google to find them. 

Just so you don't have to repeat yourself @Rehabman

You're welcome.

**Comment by RehabMan** [comment]
Just as a clarification, the issues database here at github is for bug reports.
Bug reports are where you have the skills to determine I made a mistake, or you have a suggestion for improvement.
The issues database is not for troubleshooting issues with your procedures, hardware, etc.
