### ISSUE TITLE
Hey Can u Add for a Samsung NP510R5E

### ISSUE THREAD

**Issue by The1PRimeGAmer** [RehabMan/Laptop-DSDT-Patch#51]
Hey can u add support to the laptop NP510R5E it would be really good or help me do it pls[
[DSDT.aml.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/1197762/DSDT.aml.zip)

](url)

**Comment by RehabMan** [comment]
The battery patching guide is linked from the README.
