### ISSUE TITLE
DSDT patch ``battery_ASUS-G75vw.txt`` no longer work on macOS High Sierra

### ISSUE THREAD

**Issue by TomHeaven** [RehabMan/Laptop-DSDT-Patch#52]
I just updated my Asus G60vw laptop to macOS High Sierra and found that the battery status disappeared from the status menu and the amount of electricity of battery is zero in Preferences. 

I used to make the battery work using ``battery_ASUS-G75vw.txt`` patch and your ``os-x-acpi-battery-driver`` in macOS Sierra. I tried updating them to the latest available version but the battery still not detected correctly.

I used KextWizard and found ``AppleSmartBatteryManager`` was loaded. So I guess there are some new issues that I cannot figure out.

I attached my original DSDT files extracted with Clover.

Looking forward for your help!
 
[origin.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/1343578/origin.zip)

**Comment by TomHeaven** [comment]
The battery status became normal immediately after I unplugged the power cable.  

This is quite embarrassing because I have worked for hours to solve the issue.

I'll close the issue.

**Comment by TomHeaven** [comment]
I shutdown the machine and reboot a few times. The battery status becomes normal only after I unplug the power cable. This does not affect daily usage, however, I think it can still be patched. Maybe you can find it. :)

**Comment by RehabMan** [comment]
Use the forums.
Read FAQ, "Problem Reporting"
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/

**Comment by TomHeaven** [comment]
I finally solved the problem. It turned out that I need to enable native power management first. 
By following the guide https://www.tonymacx86.com/threads/guide-native-power-management-for-laptops.175801 and using a kernel patch
```
Comment: MSR 0xE2 _xcpm_idle instant reboot (c) Pike R. Alpha
Find: 20b9e200 00000f30 
Replace: 20b9e200 00009090 
```
the battery status works correctly now.
