### ISSUE TITLE
How to fix the new series of motherboards dsdt

### ISSUE THREAD

**Issue by xpbtmusic** [RehabMan/Laptop-DSDT-Patch#53]
Hi RehabMan: 
 My computer is a desktop, dsdt is what I extracted from the windows, my motherboard is b150m-d2vx-si-cf, Intel (R) 100 Series / C230 Series Chipset Family PMC-A121, but can not find this series of fix Patch, please help me hit the patch,  can not find this series of patches on the Internet, or a patch of tools, including the new series of motherboards. There is a problem is that I extracted from the windows ssdt ,how to place it  in clover.Thank you.

**Comment by xpbtmusic** [comment]
[efi.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/1403730/efi.zip)

**Comment by xpbtmusic** [comment]
[ssdt.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/1403735/ssdt.zip)

**Comment by RehabMan** [comment]
Use the forums.

**Comment by xpbtmusic** [comment]
https://www.tonymacx86.com/threads/how-to-fix-the-new-series-of-motherboards-dsdt.235247/
