### ISSUE TITLE
Battery - Thinkpad Yoga X1 3rd Generation

### ISSUE THREAD

**Issue by cfis** [RehabMan/Laptop-DSDT-Patch#60]
Attached is a maciasl patch file enabling the battery indicator for a Yoga X1 3rd generation running on High Sierra.  I have also included the original DSDT.dsl for this laptop extracted via Clover.

This patch is based on the existing battery_Lenovo-X230i.txt, but had enough changes that I thought it was worth separating it out.

Its works with these two caveats:

* Battery indicator does not display after a reboot.  Sounds like https://github.com/RehabMan/OS-X-ACPI-Battery-Driver/issues/21. You have to turn it back on via System Preferences (when you open the Power page you can see the checkbox is checked for a split second, then it unchecks itself.  Then you manually check it and the battery indicator is back).

* When you unplug the power adapter, the indicator takes about 10 seconds to recognize the change.  On the other hand, plugging in the adapter is instantaneous and makes a nice beep sound (not sure if that is MacOS or the laptop itself).

Thanks - Charlie

[x1y3_bat.maciasl.txt](https://github.com/RehabMan/Laptop-DSDT-Patch/files/2055541/x1y3_bat.maciasl.txt)

[DSDT.dsl.txt](https://github.com/RehabMan/Laptop-DSDT-Patch/files/2055536/DSDT.dsl.txt)

**Comment by RehabMan** [comment]
Isn't this a dup of a post you already made to the tmx battery patching thread?

**Comment by cfis** [comment]
Don't think so, that must have been someone else.
Where is the tmx battery patch thread?

**Comment by RehabMan** [comment]
Battery guide thread is linked from the README.
I'd rather have changes to existing patches, where possible, instead of entirely new patch files (less files -> better).
