### ISSUE TITLE
Battery - ASUS ZenBook UX330UAR

### ISSUE THREAD

**Issue by AwlsomeAlex** [RehabMan/Laptop-DSDT-Patch#64]
Battery indicator for ASUS ZenBook UX330UA-AH55 is showing a false reading of 0% even with the DSDT Patches and the APCIBatteryManager.kext

**Comment by AwlsomeAlex** [comment]
Well even with DSDT Patches nothing is loading. Could you give me a hand with the syntax of SSDT-5.dsl? That's the only problem I got compiling! 
[UX330UAR.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/2342862/UX330UAR.zip)

**Comment by RehabMan** [comment]
Use the forums.  Link is in the README.
