### ISSUE TITLE
Error on Asus x550vx

### ISSUE THREAD

**Issue by lramadhan** [RehabMan/Laptop-DSDT-Patch#65]
First of all, correct me if i'm wrong because i'm new to this.

I wanna patch my asus x550vx battery and got suggestion to use battery_ASUS-N55SL.txt
I learn from youtube to patching by adding repo, and then browse the patch, then compile it.
But when i compiled it, i got 4 errors as i attached on this site ![Errors](https://preview.ibb.co/bZehje/Screen_Shot_2018_09_06_at_3_45_54_PM.png).

If i'm wrong to use it for x550vx, i do apologize. And hope you give some advice which one i should use for High sierra on asus x550vx.

Thanks Before.

**Comment by RehabMan** [comment]
Please use the forums for support.  Link is provided in the README.
