### ISSUE TITLE
Fix _PLD and X220 battery patches seems to not work

### ISSUE THREAD

**Issue by memegauste** [RehabMan/Laptop-DSDT-Patch#93]
So, initially I had error `8302, 6105, Invalid object type for reserved name (_PLD: found Buffer, Package required)` and I tried to fix it using `Fix _PLD...` from your patches, but it seems to be not working (not working regex due to new standards?). Then I went to `Gentoo` forums and found this:
https://forums-web2.gentoo.org/viewtopic-t-1098226-start-0.html
So I managed to fix `_PLD error`, but then I got these:
![image](https://user-images.githubusercontent.com/21007545/77109532-5c696780-6a24-11ea-914e-98887a1c2c66.png)

And fixing them using X220 battery patches is not working, I'm not familiar with MaciASL patches so I now I don't know how to fix them, also I am using this version of MaciASL:
https://github.com/acidanthera/MaciASL

**Comment by memegauste** [comment]
This is my DSDT.dsl file: https://gist.github.com/HoshiYamazaki/05e62c1f9e74ae94e5c8179d251f15fc
Dumped using this: https://github.com/corpnewt/SSDTTime

**Comment by memegauste** [comment]
Seems that iasl needs `-dl -da` command line arguments to get correct dump, I assume this as fixed then.

**Comment by kommtzeitkonrad** [comment]
The patch you are looking for can be found here: https://github.com/kylon/Laptop-DSDT-Patch/commit/60b3b9934604ca0815f15978375adf2b163c724e

```
# ToPLD
into_all all code_regex (Name\s*\(_PLD,\s*)(ToPLD\s*\([^\)]*\)) replaceall_matched
begin
%1Package() { %2 }
end;
```
